### ISSUE TITLE
 Issue with reading SMS if provider is with XXXX(Address).

### ISSUE THREAD

**Issue by Jai05-techie** [iqbalmineraltown/flutter_sms_receiver#10]
Hi, 

i have a issue with reading SMS if provider is with XXXX(Address), but if sender address is like XX-YYYY it is reading.
Help me out to solve this issue !

**Comment by iqbalmineraltown** [comment]
To my understanding, android SMS retriever does not involve the sender identity
 https://developers.google.com/identity/sms-retriever/overview
It simply matches the app hash embedded in the message, then parses the message as `String` to get the information needed. CMIIW.

On some of my actively maintained apps, the OTP sender identities are in `PascalCase` and `UPPERCASE` format
I'm not sure if I can reproduce the issue

**Comment by iqbalmineraltown** [comment]
closing as no further information provided
