### ISSUE TITLE
Which flutterplugin requests SMS permission

### ISSUE THREAD

**Issue by lcn1988** [iqbalmineraltown/flutter_sms_receiver#11]
Plugin not listening to any messages,I didn't request permission with permission_handler 5.0.1+1,

**Comment by iqbalmineraltown** [comment]
can you share your `flutter doctor -v`?

I haven't updated this for more than a year and currently doing fine on actively-maintained android apps using `flutter 1.12.13-hotfixes`
feel free to open PR if necessary

**Comment by lcn1988** [comment]
[√] Flutter (Channel master, 1.24.0-8.0.pre.252, on Microsoft Windows [Version 10.0.19042.630], locale zh-CN)
    • Flutter version 1.24.0-8.0.pre.252 
    • Framework revision bf2c9dfc05 (3 weeks ago), 2020-11-14 22:38:02 -0500
    • Engine revision 3e77d854a7
    • Dart version 2.12.0 (build 2.12.0-45.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
Android toolchain - develop for Android devices (Android SDK version 30.0.2)

**Comment by iqbalmineraltown** [comment]
did you generate the app hash and embed it on the messages?
https://developers.google.com/identity/sms-retriever/verify

**Comment by iqbalmineraltown** [comment]
closing as no further info provided
