### ISSUE TITLE
Not receiving any message

### ISSUE THREAD

**Issue by antoniocranga** [iqbalmineraltown/flutter_sms_receiver#13]
I've setup everyting correctly but is not receiving anything .

**Comment by iqbalmineraltown** [comment]
Hi, sorry to hear that
have you tried the example project?

**Comment by antoniocranga** [comment]
Hello , thank you for your response . I’ve already solved the problem . 🤗

**Comment by iqbalmineraltown** [comment]
glad to hear that!
could you share what went wrong with your setup?
I might be able to use it to improve the README manual
