### ISSUE TITLE
Not receiving any message 

### ISSUE THREAD

**Issue by bhoomesh950** [iqbalmineraltown/flutter_sms_receiver#15]
![Screenshot (138)](https://user-images.githubusercontent.com/20543788/115110136-74008000-9f97-11eb-8b13-72252132d5f5.png)

**Comment by iqbalmineraltown** [comment]
could you please elaborate on what happened

**Comment by sahilcool-nsut** [comment]
Used the same code on the pub.dev site, get the SMS Reciever Registered part, but when i recieve an SMS, it doesn't detect it. I have SMS read permissions on too.

**Comment by iqbalmineraltown** [comment]
Have you double-checked the generated hash as mentioned in the README?
I cannot do much about this part as this hash is unique to each app package name and certificate

**Comment by iqbalmineraltown** [comment]
I assume this issue has been solved as there's no response
