### ISSUE TITLE
Add support for null safety feature

### ISSUE THREAD

**Issue by devmuaz** [iqbalmineraltown/flutter_sms_receiver#16]
This package should be migrated to the latest features of the Flutter framework including the `Null-Safety`.

**Comment by iqbalmineraltown** [comment]
hi, thanks for the suggestion. I have neither the time nor urge to migrate this to null safety package as I'm still using pre-2.0 for my actively maintained apps
PRs are more than welcome!

**Comment by iqbalmineraltown** [comment]
hi i just updated the plugin to address this issue on 0.4.0
thanks
