### ISSUE TITLE
Not understand

### ISSUE THREAD

**Issue by nambui2000k** [iqbalmineraltown/flutter_sms_receiver#18]
I don't understand way to Generate acceptable message format. Can you have video example? Thanks so much.

**Comment by iqbalmineraltown** [comment]
Did you mean this tutorial which I have linked in README? https://developers.google.com/identity/sms-retriever/verify
I found it quite self-explanatory, so I don't think I am able to explain that any easier

With some quick googling, there are also some articles trying to explain those steps further
Not sure about the tutorial in video format though

and sorry, I don't have time to create a video tutorial for this 😞
