### ISSUE TITLE
Hi, Received SMS is not read in the iPhone.

### ISSUE THREAD

**Issue by akshata2406** [iqbalmineraltown/flutter_sms_receiver#19]
Hi, Received Sms is not read in the iPhone. It is working on android but facing issues in the iPhones please help.
I also used the sms plugin to read the received sms but this is also not working for iOS

**Comment by iqbalmineraltown** [comment]
as stated in the README:

> Currently developed for Android: reading messages without requesting SMS permission.

AFAIK iOS is never allowing an app to read SMS directly 
but there's should be something similar to reading OTP from iOS' System Keyboard

PRs are welcome 😄
