### ISSUE TITLE
The Example Code Doesn't even Work.

### ISSUE THREAD

**Issue by AidenEllis** [iqbalmineraltown/flutter_sms_receiver#22]
Dude, it doesn't catch any messages tf?! Tried 20+ times. Didn't catch a single sms.

**Comment by iqbalmineraltown** [comment]
I'm sorry to hear that
Have you generated and double-checked the App Hash for message format as mentioned in the README?

**Comment by AidenEllis** [comment]
Yeah, idk why it didn't work back then. Maybe i did something wrong i was in a blazing hurry XD. Anyways i'm using telephony rn and it's working as expected.

Thanks for replying ;)
