### ISSUE TITLE
Plugin not listening to any messages.

### ISSUE THREAD

**Issue by ADy1596** [iqbalmineraltown/flutter_sms_receiver#5]
I am trying to read incoming otp code for my app, plug in is not listening to any otp messages.
Here is my code. app is following all the rules of sms retriever api.

void initState() {
    super.initState();
    SharedPref.sharedPreferenceGet(StringsConstants.FCM_ID)
        .then((dynamic tempAuth) {
      authKey = tempAuth;
    });
    _updateData();
     _smsReceiver = SmsReceiver(onSmsReceived, onTimeout: onTimeout);
    _startListening();
  }

  void onSmsReceived(String message) {
    setState(() {
      _textContent = message;
      String a=_textContent;
    });
  }

  void onTimeout() {
    setState(() {
      _textContent = "Timeout!!!";
      if(_textContent=="Timeout!!!")
      {_startListening();}
    });
  }

  void _startListening() {
    _smsReceiver.startListening();
    setState(() {
      _textContent = "Waiting for messages...";
    });
  }

**Comment by iqbalmineraltown** [comment]
hi, 
did you put the app hash string in the incoming message?

**Comment by thukuwanjiku** [comment]
> hi,
> did you put the app hash string in the incoming message?

@iqbalmineraltown how should this hash string be added to the incoming message?

**Comment by iqbalmineraltown** [comment]
@thukuwanjiku ask the one who sent the message to put the hash in it 😄 

I'm quite sure I have put acceptable message format in the README, sorry if that is not clear enough

**Comment by ADy1596** [comment]
Forgot to add implementations , my bad.

**Comment by iqbalmineraltown** [comment]
cool
feel free to file a new issue if you've encountered any problems
