### ISSUE TITLE
How do i  Store hash as constant inside your app before building app package

### ISSUE THREAD

**Issue by Jai05-techie** [iqbalmineraltown/flutter_sms_receiver#6]
Hi ,

this is not issue, but have doubt

1. I downloaded `deployment_cert.der` file
2. Convert the `deployment_cert.der` file to a `.jks` file
3. By `keytool Command` i generated Hash .

now how do i store hash as constant in our app ?

**Comment by iqbalmineraltown** [comment]
no you dont store the hash in the app
just add it as part of the incoming message

**Comment by Jai05-techie** [comment]
okay thanks got it.

coz in documentation mentioned like
```
DON'T generate hash message on runtime using AppSignatureHelper. Store hash as constant inside your app before building app package.
```

so confused ! Thanks for your reply

**Comment by iqbalmineraltown** [comment]
Sorry for the confusion, I will fix the readme ASAP

what I tried to say is you need to store the hash on the app server as constant and provide it when constructing SMS

or if you need to send the hash first to the app server first, you should store this hash as constant on your app client

do not generate it at runtime as it always stays the same unless you changed the Keystore or the package name
