### ISSUE TITLE
Only safe (?.) or non-null asserted (!!.) calls are allowed

### ISSUE THREAD

**Issue by Jai05-techie** [iqbalmineraltown/flutter_sms_receiver#9]
After Updating the Android Studio and Gradle its throwing error like below,

```
"FlutterProjects/SDKFlutter/flutter/.pub-cache/hosted/pub.dartlang.org/sms_receiver-0.3.1+1/android/src/main/kotlin/com/oval/smsreceiver/SMSBroadcastReceiver.kt: (23, 32): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?"
```

help me out how to fix this ?!

**Comment by LucasSpeer** [comment]
@Jai05-techie Navigate to that file, find line 23 and change it from
`val status = extras.get(SmsRetriever.EXTRA_STATUS) as Status`
to
`val status = extras?.get(SmsRetriever.EXTRA_STATUS) as Status`

and do the same on line 29

**Comment by iqbalmineraltown** [comment]
Hi, did you use the same version as the example? 

I haven't updated this for more than a year and currently doing fine on actively-maintained apps using flutter `1.12.13-hotfixes`
I haven't got time for updating this, feel free to open PR

**Comment by iqbalmineraltown** [comment]
closing this as no updates/further information provided
feel free to reopen
